workflows:

  ios-build:

    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1

    environment:
      xcode: latest
      cocoapods: default  
      
      vars:
        XCODE_PROJECT: "MyApp.xcodeproj"
        XCODE_SCHEME: "MyApp"
        BUNDLE_ID: "com.mycompany.myapp"

    scripts:

      - name: Copy Podfile
        script: |
          cp ./ios/Podfile $CM_BUILD_DIR/ios/Podfile
          
      - name: Install dependencies
        script: |
          cd $CM_BUILD_DIR/ios
          pod install
          
      # Rest of scripts
            
    artifacts:
    
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
    
      email:
      
        recipients:
         - justjacex@gmail.com
