workflows:

  ios-build:

    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    
    integrations:
      xcode: latest
      cocoapods: default
      
    environment:
      vars:
        XCODE_PROJECT: "MyApp.xcodeproj"
        XCODE_SCHEME: "MyApp"
        BUNDLE_ID: "com.mycompany.myapp"

      xcode: latest  
      cocoapods: default

    scripts:

      - name: Install dependencies
        script: |
          pod install
          
      - name: Set bundle ID
        script: xcode-project set-bundle-id "$BUNDLE_ID" "$XCODE_PROJECT"
        
      - name: Build ipa 
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --export-method ad-hoc
            
    artifacts:
    
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
    
      email:
      
        recipients:
         - justjacex@gmail.com
